---
- name: Add MINIO_HOSTS to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.hostname }}"
    state: present
  loop: "{{ MINIO_HOSTS }}"

- name: Download Minio Binary
  get_url:
    url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
    dest: "/usr/local/bin/minio"
    mode: '0755'
  tags:
    - install

- name: Copy minio.service
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
  tags:
    - systemd

- name: Create Minio Configuration File
  template:
    src: minio.config.j2
    dest: /etc/default/minio.conf
  notify: Start Minio Service
  tags:
    - config
