---
- name: Ubuntu
  when: ansible_distribution == 'Ubuntu'
  block:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: latest
        update_cache: true
    
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker Repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
    
    - name: Update apt and install docker-ce
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

- name: CentOS
  when: ansible_distribution == 'CentOS'
  block:
   - name: Install yum utils
     yum:
       name: yum-utils
       state: latest
       update_cache: true

   - name: Add repository
     command: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
    
   - name: Update apt and install docker-ce
     yum:
       name: "{{ item }}"
       state: latest
       update_cache: true
     loop:
       - docker-ce
       - docker-ce-cli
       - containerd.io
       - docker-buildx-plugin
       - docker-compose-plugin
     notify: Start docker.serice
