---
### if you run this role with out tags this part stop the running playbook
- name: "check tags for running roles"
  fail:
    msg: "you should use tags to run playbook"
  when: 
    - ( 'all' in ansible_run_tags or not ansible_run_tags ) # if playbook run with "all" tags OR run with out tags # if use anible playbook tags use this condition - ( 'all' in ansible_playbook_tags or not ansible_playbook_tags" )

############################################################ Deb
- name: Ubuntu/Debian
  when: ansible_distribution in ["Ubuntu", "debian"]
  ignore_errors: true
  block:

    - name: "DEB: Archive /etc/apt/sources.list.d"
      archive:
        path: /etc/apt/sources.list.d
        dest: /etc/apt/sources.list.d.tar.gz

    - name: "DEB: Removing sources.list.d"
      command: rm -rf /etc/apt/sources.list.d/*

    - name: "DEB: Backup original repo file sources.list.d"
      copy:
        src: /etc/apt/sources.list
        dest: /etc/apt/sources.list.back
        backup: yes
        remote_src: yes

    - name: "DEB: Remove original repo file sources.list"
      file:
        path: /etc/apt/sources.list
        state: absent

    - name: "DEB: Add vasl-auth to /etc/apt/auth.conf.d"
      template:
        src: vasl-auth.conf.j2
        dest: /etc/apt/auth.conf.d/vasl-auth.conf
      tags:
        - add_auth_info

    - name: "DEB: Add custom repository"
      template:
        src: vasl-artifactory.list.j2
        dest: /etc/apt/sources.list.d/vasl-artifactory.list

    - name: "DEB: Install necessary packages"
      apt:
        name: "{{ item }}"
        update_cache: true
        state: present
      loop:
        - net-tools
        - vim
  tags:
    - add_repo
  
############################################################ Rpm

- name: CentOs/RHEL
  when: ansible_distribution == 'Rocky' or ansible_distribution == 'CentOS'
  ignore_errors: true
  block:

    - name: "RPM: Archive /etc/yum.repos.d"
      archive:
        path: /etc/yum.repos.d
        dest: /etc/yum.repos.d.tar.gz

    - name: "RPM: Removing yum.repos.d"
      command: rm -rf /etc/yum.repos.d/*

    - name: "RPM: Add CentOS 7 repository"
      template:
        src: centos7-artifactory.repo.j2
        dest: /etc/yum.repos.d/centos7-artifactory.repo
      when:
        - ( ansible_distribution == 'CentOS' ) and ( ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8' )

    - name: "RPM: Add Rocky repository"
      template:
        src: rocky-8-artifactory.repo.j2
        dest: /etc/yum.repos.d/rocky-8-artifactory.repo
      when:
        - ( ansible_distribution == 'Rocky' ) and ( ansible_distribution_major_version == '8' or ansible_distribution_major_version == '9' )

    - name: "RPM: Update yum cache"
      yum:
        name: "{{ item }}"
        update_cache: true
        state: present
      loop:
        - net-tools
        - vim

  tags:
    - add_repo



- name: "RPM: install custom packages"
  debug:
    msg:  "{{ ansible_distribution }}"
  when: ansible_distribution != 'Rocky' or ansible_distribution != 'CentOS' or ansible_distribution not in ["Ubuntu", "debian"]
  tags:
    - install_packages

- name: "DEB: install custom packages"
  when: ansible_distribution in ["Ubuntu", "debian"]
  ignore_errors: true
  block:
     
    - name: "DEB: Install necessary packages"
      apt:
        name: "{{ item }}"
        update_cache: true
        state: present
      loop:
        - net-tools
        - vim
        - tmux
        - telnet
        - tcpdump
        - wget
        - jq
        - curl
        - open-vm-tools
        - iftop
        - traceroute
        - htop 
        - nmap
        - nethogs
        - netcat
  tags:
    - install_packages

- name: "RPM: install custom packages"
  when: ansible_distribution == 'Rocky' or ansible_distribution == 'CentOS'
  ignore_errors: true
  block:

    - name: "RPM: Update yum cache"
      yum:
        name: "{{ item }}"
        update_cache: true
        state: present
      loop:
        - net-tools
        - vim
        - tmux
        - telnet
        - tcpdump
        - wget
        - jq
        - curl
        - open-vm-tools
        - iftop
        - traceroute
        - htop 
        - nmap
        - nethogs
        - netcat

  tags:
    - install_packages