---
- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: k3s
      tags:
        - prepareation
        - download

- hosts: master
  become: true
  roles:
    - role: k3s
      tags:
        - master

- hosts: node
  become: true
  roles:
    - role: k3s
      tags:
        - node
